// <auto-generated />
using LeaveRequests.Data.API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeaveRequests.Migrations
{
    [DbContext(typeof(LeaveRequestsContext))]
    partial class LeaveRequestsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("LeaveRequests.Data.API.Model.SimpleLeaveRequestDto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("daysRequested")
                        .HasColumnType("TEXT");

                    b.Property<string>("employeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("employeeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("leaveReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("requestDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("requestStatus")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
